### PR TITLE
Patch to make this gem work with Rails 2 

### PR DESCRIPTION
**Pull request by alexrothenberg**
Patch to make this gem work with Rails 2 - the order it loads gems is different in Rails 2 and Rails 3 since we don't have Railties and the initializer block in Rails2

### CODE REVIEW

**Comment by justinko** [comment]
Hmmm, I am not able to _not_ get this to work with the current code base in Rails 2. Can you paste your Gemfile?

**Comment by alexrothenberg** [comment]
Justin

Here's my sunspot.yml

```
development:
  solr:
    hostname: solr.alexrothenberg.com
    port: 8080
    path: /solr/myapp
    user: me
    password: password
```

Without the patch the url does not have the basic auth
```    $ script/console 
    ruby-1.8.7-p302 :001 > Sunspot.session
     => #<Sunspot::SessionProxy::ThreadLocalSessionProxy:0x106f69e40 @config=#<LightConfig::Configuration:0x106f6c000 @properties={:pagination=>#<LightConfig::Configuration:0x106f6b6a0 @properties={:default_per_page=>30}>, :master_solr=>#<LightConfig::Configuration:0x106f6ba88 @properties={:url=>nil}>, :solr=>#<LightConfig::Configuration:0x106f6be98 @properties={:url=>"http://solr.alexrothenberg.com:8080/solr/myapp"}>}>>

``````
With the patch it does
```  $ script/console 
  ruby-1.8.7-p302 :001 > Sunspot.session
  => #<Sunspot::SessionProxy::ThreadLocalSessionProxy:0x1068f23a0 @config=#<LightConfig::Configuration:0x10691c4c0 @properties={:pagination=>#<LightConfig::Configuration:0x10691bb10 @properties={:default_per_page=>30}>, :master_solr=>#<LightConfig::Configuration:0x10691bef8 @properties={:url=>nil}>, :solr=>#<LightConfig::Configuration:0x10691c308 @properties={:url=>"http://me:password@solr.alexrothenberg.com:8080/solr/myapp"}>}>> 
``````

**Comment by justinko** [comment]
Okay, I understand the problem now. Thanks for the patch Alex. I've pushed 0.0.2

**Comment by alexrothenberg** [comment]
Thanks Justin

sunspot_rails initializes itself differently for Rails2 & 3 -> https://github.com/outoftime/sunspot/blob/master/sunspot_rails/lib/sunspot_rails.rb. In Rails2 it creates the session as the gem is loaded (before this gem overrides the methods) but in Rails3 it uses Railties and the initializer block until after all the gems are loaded.

**Comment by justinko** [comment]
Yep.

One solution for Rails 2 is to add `Sunspot.session = Sunspot::Rails.build_session` in a config/initializers file. But I agree that this gem should handle that for them.

**Pull request merged**
